#!/bin/sh -
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Usage: baudrates.sh output [macro_def_files]
#
#  macro_def_files are optional lists of macros defined by <termios.h>,
#  obtained e.g. by using the -dM option to gcc -E.
#
# If there are baud rates available on any systems which are not listed
# here, add them to this list, please.
#

out="$1"
if [ x"$out" != x ]; then
	shift
	exec >"$out"		# Redirect remaining output
fi

s='[[:space:]]'
baudrates=`(
    for b in 50 75 110 134 150 200 300 600 1200 1800 2400 4800 \
		7200 9600 14400 19200 28800 33600 38400 57600 76800 \
		115200 128000 153600 230400 256000 307200 460800 \
		500000 576000 614400 921600 1000000 1152000 1500000 \
		2000000 2500000 3000000 3500000 4000000 5000000 10000000
    do
	echo "#define B$b -"
    done
    cat -- "$@" < /dev/null
) |
    sed -E -n -e "s/^$s*#$s*define$s$s*B([1-9][0-9]*)$s.*\$/\\1/p" |
    sort -n | uniq`

printf '/* This file is autogenerated by %s */\n\n' `basename "$0"`
printf '#if\tB0 == 0'
for b in $baudrates; do
	printf ' \\\n\t&& (!defined(B%u) || (B%u == %u))' $b $b $b
done
printf '\n#define SPEED_T_IS_SANE 1\n#else\n\n'

# Baudrate table

printf '#ifdef MAKE_BAUD_TABLE\n'
printf 'static const struct std_baudrate MAKE_BAUD_TABLE [] = {\n'
for b in $baudrates; do
	printf '#ifdef B%u\n\t{ B%u, %u },\n#endif\n' $b $b $b
done
printf '};\n'
printf '#define NUM_STD_BAUDRATES ARRAY_SIZE(MAKE_BAUD_TABLE)\n'
printf '#endif /* MAKE_BAUD_TABLE */\n'
printf '\n#endif /* SPEED_T_IS_SANE */\n'
